##########################################
# Program detects 3' ends of transcripts #
##########################################


########################################
# Source of FASTQ.GZ files.       #
# Should be .fq.gz or .fastq.gz files. #
########################################

INPUT-DIR: /media/root/ngs_nas3/2019_05_13_Microbiome_lncRNA_M13/Microbiome_GMC 
SAMPLES: ODN-1 ODN-5 
LANE-REGEX: "L\\d\\d\\d_"
TMP-DIR: tmp_coliold
OUT-DIR: output_coliold
SCRATCH: tmp_coli
BENCH-DIR: bench_coli
BENCHMARKS: benchmarks

#############################
# Primer sequences fltering #
#############################
rRNA: datasets/bbmap/rRNA_coli.fa 
PRIMERS:
    R1: datasets/bbmap/R1_for.fasta #sequences that must occure in R1
    R1_k: 15 #minimum lenth of substring to match
    R2: datasets/bbmap/R1_rev.fasta #sequences that must not occure in R1
    R2_k: 15 #minimum lenth of substring to match

ASSEMBLER: SPADES  #SPADES # BBMERGE 
#Parameters for filterin out 16S havving reads
16S:
    DB:
        fasta: /media/root/ocean/Databases/SILVA/SILVA_132_SSURef_Nr99_tax_silva.fasta
        k: 40 # kmer matching 16S for reads filtering
    hmm: 
        model: /mnt/beegfs/Databases/SILVA/SILVA_132_SSURef_Nr99_tax_silva_full_align_trunc_bacteria_0.95_nd_dn.hmm 
        e: 1000
        ts: 560    
        te: 600
        rs: 1
        re: 70
        length: 30 #match length in read

min_contig_length: 300
max_contig_length: 12000000000
clustering_frac: 0.95
ref: /mnt/beegfs/Databases/BACTERIA/k12_viktorijai/genome.fa 
#########################
# CPU and memory params #
#########################
MACHINE:
    threads_julia: 12
    memory_java: 4
    threads_sambamba: 8
    threads_spades: 12
    threads_barnap: 12
    threads_cdhit: 12
    threads_nhmmer: 12
    threads_bwa: 12
    threads_salmon: 12
    threads_kraken: 12

##############
# References #
##############
REFERENCE: datasets/small_dataset/references/GRCh38.primary_assembly.chr21_reduced.fa
TRANSCRIPTS:
GFF3: datasets/small_dataset/references/gencode.v28.primary_assembly.annotation_chr21_reduced.gff3
GTF: datasets/small_dataset/references/gencode.v28.primary_assembly.annotation_chr21_reduced.gtf
###################
# Fastqc options. #
###################
FASTQC:
    kmer_size: 5   # [5]

############
# Trimming #
############
BBDUK:
    threads: 8
    ref: datasets/bbmap/two_short.fa
    ktrim: r
    k: 23
    mink: 11
    hdist: 1
    minlength: 100
    maxns: 1
    qtrim: r
    trimq: 15
    additional_params: "tpe tbo"

###############
# Subsampling #
###############
SUBSAMPLING:
    threads: 4
    run: False
    subsample_to:

#############
# Alignment #
#############
MAPPING:
    STAR:
        threads: 24
        chimSegmentMin: 20
        additional_params: ""

####################
# Annotation of TS #
####################
ANNOTATE-TS:
    threads: 1
    k: 10
    m: 1
    mappingquality: 0              # [0] Only reads with greater than this mapping value will pass.
    strandedness:                  # List your SAMPLES and provide strandedness.
        HBR_100_Collibri_chr21small_A: "+" # [+] If R1 read is the same as a gene sequence: +; If R2 read is the same as a gene sequence: -;
    additional_params: "--cluster" # ["--cluster --verbose"]
KRAKEN_DB: /mnt/beegfs/Databases/KRAKEN/20190424_standard
