###########################################################################
# Program assembled 16S fragment+proximal genomic region and analyse them #
###########################################################################

####################
# Input & output   #
####################

KRAKEN_DB: datasets/testingdata/remote/kraken/bacteria_202011min 
DADA_DB: datasets/testingdata/remote/dada2/RefSeq-RDP16S_v2_May2018.fa.gz 
DADA_DB_species:  datasets/testingdata/remote/dada2/RefSeq-RDP_dada2_assignment_species.fa.gz  
BLAST_DB_contigs: datasets/testingdata/expected_contigs/zymo_expected_contigs.fa
BLAST_DB_nt: datasets/testingdata/remote/ntsmall/zymo  
SAMPLES:  Zymo10.1Sim # fastq.gz  files, having this fragment in names will be used as input
INPUT-DIR: datasets/testingdata/remote/zymo_simulated_real_insert_distribution # Input dir
LANE-REGEX: "L\\d\\d\\d_" # Most probably you do not need  to change this
TMP-DIR: example/tmp  # change 'exaample' into your desired output folder name
OUT-DIR: example/out  # change 'exaample' into your desired output folder name !!!!! RESULTS WILL BE HERE 
SCRATCH: example/tmp  # change 'exaample' into your desired output folder name
BENCH-DIR:  example/bench  # change 'exaample' into your desired output folder name 
BENCHMARKS: example/benchmarks  # change 'exaample' into your desired output folder name 

###############
# Databases   #
###############

KRAKEN_DB: datasets/testingdata/remote/kraken/bacteria_202011min # Kraken2 database. Joined contigs, reads and pseudo contigs are classified against it. 
DADA_DB: datasets/testingdata/remote/dada2/RefSeq-RDP16S_v2_May2018.fa.gz # Dada2 database for genus level assignments.
DADA_DB_species:  datasets/testingdata/remote/dada2/RefSeq-RDP_dada2_assignment_species.fa.gz # Dada2 database for species level assignments. 
BLAST_DB_nt: datasets/testingdata/remote/ntsmall/zymo  # blast database  - full nt is required for optimal performance.   

# !!! Sections below should be changed only if you know what you are doing !!! 
# Could consider changing trimq value in BBDUK section, or downsampling parameters in Subsampling section. 

############
# Trimming #
############
BBDUK:
    threads: 8
    ref: datasets/bbmap/two_short.fa
    ktrim: r
    k: 23
    mink: 11
    hdist: 1
    minlength: 250
    maxns: 0
    qtrim: r
    trimq: 20 
    additional_params: "tpe tbo"

###############
# Subsampling #
###############
SUBSAMPLING:
    threads: 4
    run: False # if set to True reads of samples will be downsampled to the lowest number or the number indicated below
    subsample_to:  # if a number is given - reads of all samples will be downsampled to it.

#############################
# Primer sequences fltering #
#############################
PRIMERS:
    R1: datasets/bbmap/R1_v3.fasta #sequences that must occure in R1
    R1_4trim: datasets/bbmap/R1_v3_4trim.fasta #sequences that must occure in R1
    R1_4trim2: datasets/bbmap/R1_v3_4trim2.fasta #sequences that must occure in R1
    R1_k: 15 #minimum lenth of substring to match
    R2: datasets/bbmap/R2_v3.fasta #sequences that must not occure in R1
    R2_k: 15 #minimum lenth of substring to match

#Parameters for filterin out 16S havving reads
16S:
    hmm_reads:
        model: datasets/SILVA_132_SSURef_Nr99_tax_silva_full_align_trunc_bacteria_0.95_nd_dn.hmm
        e: 1000
        ts: 600
        te: 1000
        rs: 1
        re: 350
        length: 200 #match length in read
        max_R2_fraction: 0.3

#########################
# CPU and memory params #
#########################
MACHINE:
    threads_julia: 4
    memory_java: 4
    threads_sambamba: 4
    threads_spades: 4
    threads_barnap: 4
    threads_cdhit: 4
    threads_nhmmer: 24
    threads_bwa: 4
    threads_salmon: 4
    threads_kraken: 4
    threads_blast: 4
    threads_swarm: 4
    threads_dada: 8

###################
# Fastqc options. #
###################
FASTQC:
    kmer_size: 5   # [5]

